twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        app_title: '%env(APP_TITLE)%'
        app_csrf_token: '%env(SECURITY_TOKEN)%'
    form_themes: ['bootstrap_4_layout.html.twig']